import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Projects Learning</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 style={{ textAlign: 'center', textTransform: 'uppercase' }}>
        Hello World
      </h1>
    </div>
  );
};

export default Home;
