import type { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import styled from 'styled-components';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Projects Learning</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomeContent>
        <HomeTitle>Welcome to my blog</HomeTitle>
        <HomeDescription>
          Here we testing Next JS with TypeScript
        </HomeDescription>
        <Link href='/blog'>
          <a style={{ marginTop: '50px' }}>Redirect to my blog</a>
        </Link>
      </HomeContent>
    </>
  );
};

export default Home;

const HomeContent = styled.section`
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const HomeTitle = styled.h2`
  text-transform: uppercase;
  font-size: clamp(25px, 5vw, 50px);
`;

const HomeDescription = styled.p`
  font-size: clamp(15px, 3vw, 30px);
`;
